### ISSUE TITLE
tensorboard

### ISSUE THREAD

**Issue by zzchuman** [xingminw/learn-signal-control#1]
Hello, I want to use the tensorboard via rllib. But, I can not find how to config it? Could you teach me?

**Comment by xingminw** [comment]
After installing the tensorboard, you can try
`tensorboard --logdir=$results path`
the `$results path` is the  store the output, if you are using ubuntu, it is likely `~/ray-results`.

**Comment by zzchuman** [comment]
> 安装张量板后，您可以尝试
> `tensorboard --logdir=$results path`
> 将`$results path`输出存储起来，如果您使用的是ubuntu，则很有可能`~/ray-results`。

OK， thank you! I have a try.
